# pluginexecdir = /usr/bin/enigma2/python/Plugins/Extensions/PermanentTimeshift
timeshiftincludedir = /usr/bin/enigma2/python/Plugins/Extensions/PermanentTimeshift
createapscfiles_SOURCES = createapscfiles.cc

