pluginexecdir = /usr/bin/enigma2/python/Plugins/Extensions/PermanentTimeshift
pluginexec_PROGRAMS = /usr/bin/enigma2/python/Plugins/Extensions/createapscfiles
timeshift_createapscfiles_SOURCES = timeshift/createapscfiles.cc

# timeshiftincludedir = $(pkgincludedir)timeshift/createapscfiles
# createapscfiles_SOURCES = createapscfiles.cc
